/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseModalDialog: typeof import('./src/components/common/BaseModalDialog.vue')['default']
    ContrastOutline: typeof import('./src/components/Icons/ContrastOutline.vue')['default']
    IconButton: typeof import('./src/components/common/IconButton.vue')['default']
    Loader: typeof import('./src/components/Icons/Loader.vue')['default']
    MoonOutline: typeof import('./src/components/Icons/MoonOutline.vue')['default']
    NameDialog: typeof import('./src/components/common/NameDialog.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NTree: typeof import('naive-ui')['NTree']
    Pin32Filled: typeof import('./src/components/Icons/Pin32Filled.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchOutline: typeof import('./src/components/Icons/SearchOutline.vue')['default']
    Setting: typeof import('./src/components/Icons/Setting.vue')['default']
    SlideAdd48Filled: typeof import('./src/components/Icons/SlideAdd48Filled.vue')['default']
    SunnyOutline: typeof import('./src/components/Icons/SunnyOutline.vue')['default']
    WindowClose: typeof import('./src/components/Icons/WindowClose.vue')['default']
    WindowHidden: typeof import('./src/components/Icons/WindowHidden.vue')['default']
    WindowMax: typeof import('./src/components/Icons/WindowMax.vue')['default']
    WindowMin: typeof import('./src/components/Icons/WindowMin.vue')['default']
    WindowRestore: typeof import('./src/components/Icons/WindowRestore.vue')['default']
  }
}
