// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {controller} from '../models';

export function GetCtx():Promise<context.Context>;

export function IsEncrypted():Promise<controller.Res>;

export function IsLogin():Promise<controller.Res>;

export function IsRegister():Promise<controller.Res>;

export function Login(arg1:string):Promise<controller.Res>;

export function Logout():Promise<controller.Res>;

export function ModifyPassword(arg1:string,arg2:string,arg3:string):Promise<controller.Res>;

export function Register(arg1:string,arg2:string):Promise<controller.Res>;

export function SetCtx(arg1:context.Context):Promise<void>;
