// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCtx() {
  return window['go']['controller']['Auth']['GetCtx']();
}

export function IsEncrypted() {
  return window['go']['controller']['Auth']['IsEncrypted']();
}

export function IsLogin() {
  return window['go']['controller']['Auth']['IsLogin']();
}

export function IsRegister() {
  return window['go']['controller']['Auth']['IsRegister']();
}

export function Login(arg1) {
  return window['go']['controller']['Auth']['Login'](arg1);
}

export function Logout() {
  return window['go']['controller']['Auth']['Logout']();
}

export function ModifyPassword(arg1, arg2, arg3) {
  return window['go']['controller']['Auth']['ModifyPassword'](arg1, arg2, arg3);
}

export function Register(arg1, arg2) {
  return window['go']['controller']['Auth']['Register'](arg1, arg2);
}

export function SetCtx(arg1) {
  return window['go']['controller']['Auth']['SetCtx'](arg1);
}
