// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';
import {context} from '../models';

export function GetAppSettingAttr(arg1:string):Promise<controller.Res>;

export function GetCtx():Promise<context.Context>;

export function SetAppIcon(arg1:Array<number>):Promise<void>;

export function SetAppSettingAttr(arg1:string,arg2:any):Promise<void>;

export function SetCtx(arg1:context.Context):Promise<void>;
