// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppSettingAttr(arg1) {
  return window['go']['controller']['Config']['GetAppSettingAttr'](arg1);
}

export function GetCtx() {
  return window['go']['controller']['Config']['GetCtx']();
}

export function SetAppIcon(arg1) {
  return window['go']['controller']['Config']['SetAppIcon'](arg1);
}

export function SetAppSettingAttr(arg1, arg2) {
  return window['go']['controller']['Config']['SetAppSettingAttr'](arg1, arg2);
}

export function SetCtx(arg1) {
  return window['go']['controller']['Config']['SetCtx'](arg1);
}
