// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFolder(arg1, arg2, arg3) {
  return window['go']['controller']['FileSystem']['CreateFolder'](arg1, arg2, arg3);
}

export function GetAllFolders() {
  return window['go']['controller']['FileSystem']['GetAllFolders']();
}

export function GetCtx() {
  return window['go']['controller']['FileSystem']['GetCtx']();
}

export function SetCtx(arg1) {
  return window['go']['controller']['FileSystem']['SetCtx'](arg1);
}
