// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';
import {context} from '../models';

export function CreateFolder(arg1:string,arg2:number):Promise<controller.Res>;

export function DeleteFolder(arg1:number):Promise<controller.Res>;

export function GetCtx():Promise<context.Context>;

export function GetStorage():Promise<controller.Res>;

export function RenameFolder(arg1:string,arg2:number):Promise<controller.Res>;

export function SetCtx(arg1:context.Context):Promise<void>;
