// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';
import {context} from '../models';

export function CreateFolder(arg1:string,arg2:number,arg3:string):Promise<controller.Res>;

export function GetAllFolders():Promise<controller.Res>;

export function GetCtx():Promise<context.Context>;

export function SetCtx(arg1:context.Context):Promise<void>;
