// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFolder(arg1, arg2) {
  return window['go']['controller']['FileSystem']['CreateFolder'](arg1, arg2);
}

export function DeleteFolder(arg1) {
  return window['go']['controller']['FileSystem']['DeleteFolder'](arg1);
}

export function GetCtx() {
  return window['go']['controller']['FileSystem']['GetCtx']();
}

export function GetStorage() {
  return window['go']['controller']['FileSystem']['GetStorage']();
}

export function RenameFolder(arg1, arg2) {
  return window['go']['controller']['FileSystem']['RenameFolder'](arg1, arg2);
}

export function SetCtx(arg1) {
  return window['go']['controller']['FileSystem']['SetCtx'](arg1);
}
